# Generated by Django 3.0 on 2020-08-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Maths'), ('C', 'Chemistry'), ('P', 'Pysics')], max_length=10)),
                ('reference_no', models.BigIntegerField()),
                ('CREATED_ON', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATED_ON', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
