# Generated by Django 3.0 on 2020-08-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='discription',
            new_name='description',
        ),
    ]
